// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniFlowHub.Api.Data;

#nullable disable

namespace UniFlowHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622134241_AddGestaoPessoasCargosEpisColaboradores")]
    partial class AddGestaoPessoasCargosEpisColaboradores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniFlowHub.Api.Models.BaseConhecimentoTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArquivoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("BaseConhecimentoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoArquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjUnidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportadoPorUserId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("CartaoPontoArquivo");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaoPontoArquivoId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConfirmadoPeloUsuario")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEdicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRespostaUsuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("FuncionarioNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioEditado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinhaOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrecisaAjuste")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartaoPontoArquivoId");

                    b.HasIndex("EditadoPorUserId");

                    b.ToTable("CartaoPontoRegistro");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadoTIComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ChamadoTIId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoTIId");

                    b.ToTable("ChamadoTIComunicacao");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcessoRemotoSenha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RustDeskSenha");

                    b.Property<string>("AcessoRemotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnexoImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrimeiroEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataReabertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipamentoSistemaOperacional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesAprovacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesEncerramento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Reaberto")
                        .HasColumnType("boolean");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SatisfacaoComentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SatisfacaoNota")
                        .HasColumnType("integer");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("ChamadoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.EquipamentoTI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevistaRetorno")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<int?>("ExcluidoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("FilialCompra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FilialCompraId")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotivoExclusao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotaFiscalCompra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patrimonio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioResponsavelDepartamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioResponsavelEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioResponsavelNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioResponsavelUnidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("EquipamentoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("GestaoPessoasCargo");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasCargoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CargoId", "ItemId")
                        .IsUnique();

                    b.ToTable("GestaoPessoasCargoItem");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("Cpf");

                    b.HasIndex("UnidadeId");

                    b.ToTable("GestaoPessoasColaborador");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasColaboradorRetirada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("ItemId");

                    b.ToTable("GestaoPessoasColaboradorRetirada");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("TipoProcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TipoProcesso", "Ordem");

                    b.ToTable("GestaoPessoasEtapa");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Nome", "Tamanho");

                    b.ToTable("GestaoPessoasItem");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasProcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AprovadorGestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColaboradorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAprovacaoGestor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EtapaAtualId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoCancelamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesAprovacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoProcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtapaAtualId");

                    b.HasIndex("Userid");

                    b.ToTable("GestaoPessoasProcesso");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasProcessoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EtapaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("ProcessoId");

                    b.ToTable("GestaoPessoasProcessoHistorico");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GuiaIcmsPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuiaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUserId");

                    b.HasIndex("GuiaId")
                        .IsUnique();

                    b.ToTable("GuiaIcmsPagamento");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PecaVendedorMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CpfVendedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeVendedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMeta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMeta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUserId");

                    b.HasIndex("CpfVendedor");

                    b.HasIndex("CpfVendedor", "Origem", "TipoMeta", "DataInicio", "DataFim");

                    b.ToTable("PecaVendedorMeta");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PerfilSistema");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistemaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilSistemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilSistemaId", "Chave")
                        .IsUnique();

                    b.ToTable("PerfilSistemaAcesso");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistemaEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaNumero")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilSistemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilSistemaId", "EmpresaNumero")
                        .IsUnique();

                    b.ToTable("PerfilSistemaEmpresa");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aprovador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comprador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEnvioCompras")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FornecedorSugerido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesAprovacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesCompras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("SolicitacaoCompra");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompraComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitacaoCompraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoCompraId");

                    b.ToTable("SolicitacaoCompraComunicacao");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoRHComunicacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AutorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitacaoRHId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoRHId");

                    b.ToTable("SolicitacaoRHComunicacao");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnexossUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Aprovada")
                        .HasColumnType("boolean");

                    b.Property<string>("Aprovador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesAprovacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacoesEncerramento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SatisfacaoComentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SatisfacaoNota")
                        .HasColumnType("integer");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSolicitacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("SolicitacaoRH");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroRevenda")
                        .HasColumnType("integer");

                    b.Property<string>("Revenda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.UserPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Perfil")
                        .IsUnique();

                    b.ToTable("UserPerfil");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.VeiculoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtualizadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Reservado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorUserId");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.ToTable("VeiculoReserva");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.BaseConhecimentoTI", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoArquivo", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "ImportadoPorUser")
                        .WithMany()
                        .HasForeignKey("ImportadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImportadoPorUser");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoRegistro", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.CartaoPontoArquivo", "Arquivo")
                        .WithMany("Registros")
                        .HasForeignKey("CartaoPontoArquivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.Users", "EditadoPorUser")
                        .WithMany()
                        .HasForeignKey("EditadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arquivo");

                    b.Navigation("EditadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadoTIComunicacao", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.ChamadosTI", "ChamadoTI")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("ChamadoTIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChamadoTI");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.EquipamentoTI", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasCargoItem", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasCargo", "Cargo")
                        .WithMany("Itens")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasItem", "Item")
                        .WithMany("Cargos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasColaborador", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasCargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniFlowHub.Api.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cargo");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasColaboradorRetirada", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasColaborador", "Colaborador")
                        .WithMany("Retiradas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasItem", "Item")
                        .WithMany("Retiradas")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasProcesso", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasEtapa", "EtapaAtual")
                        .WithMany()
                        .HasForeignKey("EtapaAtualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EtapaAtual");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasProcessoHistorico", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasEtapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniFlowHub.Api.Models.GestaoPessoasProcesso", "Processo")
                        .WithMany("Historico")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etapa");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GuiaIcmsPagamento", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "AtualizadoPorUser")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtualizadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PecaVendedorMeta", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "AtualizadoPorUser")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtualizadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistemaAcesso", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.PerfilSistema", "PerfilSistema")
                        .WithMany("Acessos")
                        .HasForeignKey("PerfilSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilSistema");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistemaEmpresa", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.PerfilSistema", "PerfilSistema")
                        .WithMany("Empresas")
                        .HasForeignKey("PerfilSistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilSistema");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompraComunicacao", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.SolicitacaoCompra", "SolicitacaoCompra")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("SolicitacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoCompra");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoRHComunicacao", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.SolicitacoesRH", "SolicitacaoRH")
                        .WithMany("Comunicacoes")
                        .HasForeignKey("SolicitacaoRHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoRH");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Unidade", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Empresa", "EmpresaCadastro")
                        .WithMany("Revendas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmpresaCadastro");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.UserPerfil", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "User")
                        .WithMany("Perfis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Users", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniFlowHub.Api.Models.Unidade", "Unidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.VeiculoReserva", b =>
                {
                    b.HasOne("UniFlowHub.Api.Models.Users", "AtualizadoPorUser")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtualizadoPorUser");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.CartaoPontoArquivo", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.ChamadosTI", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Empresa", b =>
                {
                    b.Navigation("Revendas");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasCargo", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasColaborador", b =>
                {
                    b.Navigation("Retiradas");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasItem", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Retiradas");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.GestaoPessoasProcesso", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.PerfilSistema", b =>
                {
                    b.Navigation("Acessos");

                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacaoCompra", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.SolicitacoesRH", b =>
                {
                    b.Navigation("Comunicacoes");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Unidade", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("UniFlowHub.Api.Models.Users", b =>
                {
                    b.Navigation("CreatedUsers");

                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
